### PR TITLE
Consolidate code and update deprecated calls.

### PR DESCRIPTION
**Pull request by daemongh**
The `index.html` file was starting to get littered with a lot of inline scripts and I thought it would make sense to pull those out and stick them in what was `load-src.js`.  I also took the liberty of renaming that file since it now holds code that more than just loads the `src` of the webview.

There were several deprecation warnings that showed up when I updated to the latest electron-prebuilt and electron-packager, namely the `loadUrl` function (used for loading the index file at app startup) and the `ipc` module (used for notifications and other communication with the webview), so I went ahead and updated them to the new recommended stuff.

And lastly a small feature: displaying the version in the title bar of the window and appending the webview title (which changes on channel/room changes in Mattermost) to it.

### CODE REVIEW

**Comment by lloeki** [comment]
Fantastic! This was second to next in line on my TODO. I'll review this ASAP.

**Comment by lloeki** [comment]
There are many things going on there, including various fixes and feature additions so I need a little more time to ponder on this. Anyway, won't merge until we can get what causes #37.

**Comment by LongLiveCHIEF** [comment]
I think we should cherry-pick 92c8716 and 91ba75e and merge them into #47, to craft our next minor release.

**Comment by geekytime** [comment]
> I think we should cherry-pick 92c8716 and 91ba75e and merge them into #47, to craft our next minor release.

If we just want those two commits I can pull them over into their own branch easily enough. Let's not clutter #47 with unrelated code. It's kind of big already.

**Comment by lloeki** [comment]
@geekytime agreed

**Comment by LongLiveCHIEF** [comment]
Let's do that.

**Pull request closed without merging**
