### PR TITLE
Switch config to nconf

### PR DESCRIPTION
**Pull request by geekytime**
This moves the app config into a settings module that is built around nconf. This will allow us to have a nicely layered configuration system, including default values, command-line args, and multiple config files. We could also support environment variables if necessary.

I've moved the team urls into the app state and put it in an array, as a step toward supporting having multiple teams open at the same time, which is my main goal right now.

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
Can you update the README with the new usage/build instructions this would entail?

**Comment by geekytime** [comment]
> Can you update the README with the new usage/build instructions this would entail?

Yup. Sorry.

**Comment by LongLiveCHIEF** [comment]
The `state.json` object needs to be configured so that you can set up a server, without specifying teams (teams are optional, servers are not).  the conf should focus on `state.host` instead of `state.teams`. I think the object that results by the time it resolves from nconf should look like this (the server/teams piece anyways):

``` json
{
  "hosts": [{
    "url": "http://some.mattermost.com/",
    "teams":[{
        "name":"team1",
        "path":"/team-1" 
    },{
        "name":"team2",
        "path":"/team-2"
    }] 
  }],
  "window": {
    "width": 800
  }
}
```

Each `host` object would then also be able to take other configuration parameters we need to be able to add down the road, such as `proxy`, `cert`, `certPath`, and an `auth` object for configuration of auth protocol params (such as Oath2 endpoints and keys/secrets, or LDAP server bind info)

**Comment by geekytime** [comment]
> Each host object would then also be able to take other configuration parameters we need to be able to add down the road, such as proxy, cert, certPath, and an auth object for configuration of auth protocol params (such as Oath2 endpoints and keys/secrets, or LDAP server bind info)

Why should we make this more complicated than it needs to be? Since Mattermost currently thinks in teams, I think we should probably wait and do this once Mattermost and Matterfront support any of this stuff.

This is especially true for the auth stuff. I don't think we want Matterfront to EVER store credentials or secrets or anything, since Mattermost will want to do that, and then use cookies or tokens for auth.

**Comment by geekytime** [comment]
By storing the teams in the state, we make it simple for the user to simply copy/paste the url for their team right into Matterfront.

I'd rather wait and see what kinds of config is actually required by us and our other users moving forward, and expand this at that point based on our actual needs.

**Comment by geekytime** [comment]
> (teams are optional, servers are not)

But humans don't think in terms of servers. They think in terms of teams. There are some things that Matterfront just doesn't need to be able to do, and I think connecting to the general server and signing up for new teams could be one of those, at least at first.

**Comment by LongLiveCHIEF** [comment]
You're thinking humans... a.k.a individual one off users. I'm thinking IT admins, responsible for the configuration and build of the executable (which is where the configuration lies), which they distribute to their organization... which has _n_ number of teams.

Things like the `host` settings I described are also organization level settings.

Mattermost does not actually think in teams, it thinks in organizations. The average everyday user is just unable to see the organization level features.  Matterfront needs those features.

Mattermost also has the concept of "team directories", and has features designed to allow an onboarding process that depends on the user being able to visit the "home" page. These are features that don't exist in Slack.

The nature of the Mattermost "home screen" will continue to evolve and play a more important role for organizations, and it's a simple matter for us to change the config structure now to easily accommodate this now and into the future. (so that we can allow either users OR admins to decide which experience they want to deliver with the compiled executable).

**Comment by LongLiveCHIEF** [comment]
> I'd rather wait and see what kinds of config is actually required by us and our other users moving forward, and expand this at that point based on our actual needs.

We've already had these discussions though. As a new contributor, you might see it as a wait and see... while for us, we've already been through that phase, and are just trying to explain the outcome and what we need to support.

**Comment by geekytime** [comment]
> As a new contributor, you might see it as a wait and see... 

It's not a "wait and see whether we need it", it's a "wait and see the best way to implement it". I tend to apply the KISS principle first, and only make things complex when they _need_ to get complex. Small, iterative changes that support the current needs.

You're thinking ahead to features that don't exist, yet: http://www.danielsen.com/jokes/objecttoaster.txt

**Comment by LongLiveCHIEF** [comment]
Let me take a quick nap and consider your arguments. Check back in about 90
minutes.

Maybe @lloeki will have had a chance to share any thoughts on this
implementation by then.

**Comment by LongLiveCHIEF** [comment]
ok, so thought about this. You are right that it should be teams. _However_, There _will_ need to be a host at the same level as `window`, and those org-level properties such as proxy/auth/etc... will also be at that level.

That's something that we can do in the future though.

**Comment by lloeki** [comment]
Sorry for not chiming in :-/ very busy ATM.

**Comment by LongLiveCHIEF** [comment]
no worries. Just let us know if you have issues with any of our PR's. I have a good feel for what you would want to see in code reviews, so I'm trying to make sure I cover any concerns you would have brought up if you haven't been able to comment.

**Pull request merged**
