### PR TITLE
Show a tray icon if enabled in the config.

### PR DESCRIPTION
**Pull request by teetrinkers**
So here's a first cut for #80. What do you think of the icons?

Do you know if there's a way to mock the electron apis? I'd like to write a unit test for tray.js, but I'm not a js expert.

I'll test it on windows when I'm back at work on monday. I think for windows we should hide the window instead of quitting the app when the user closes the window and the tray icon is enabled.

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
I can test on Windows here in a bit, but there are a few things we'll need to do in order to merge:
- ~~[ ] Change the icon to match the icon [colors of Matterfront](https://raw.githubusercontent.com/lloeki/matterfront/master/resources/mattermost.ico)~~
- [x] Create tests for this
- [ ] Wire both these events, and the team mention badges into a more organized event system
- [x] Remove the use of `const`. We're not ready to have the "js style guide conversation" within our group yet, so stick to `var` unless it's logically necessary to use `let` somewhere.

I can help with the tests and the organizing of events.  I'm going to create a branch soon, and will use your commit's as the HEAD of that branch, and we can work together on committing to that branch to work this into either 1.3 or 1.4 release.

**Comment by LongLiveCHIEF** [comment]
I had a side conversation with @lloeki, and if he's agreeable to what we've discussed, then I'd prefer to make @teetrinkers a collaborator after migration to org.

**Comment by teetrinkers** [comment]
>  Change the icon to match the icon colors of Matterfront

I think the menu bar icon should be colorless except for notifications. On my Macbook, the only colored menu icon is the input language selector. Apple recommends to use a template image (monochrome image) in their OS X Human Interface Guidleines: https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/MenuBarMenus.html#//apple_ref/doc/uid/20000957-CH29-SW1

I think Windows is also moving towards monochrome icons in the notification area (note the dropbox icon):
Windows 10

**Comment by LongLiveCHIEF** [comment]
good points. Let's scratch that one.

**Comment by lloeki** [comment]
IMO system-tied elements should comply with the platform the app is running on. A good platform citizen blends with its environment. In this case that'll mean an icon set per platform. Dropbox is a good guideline for that.

**Comment by teetrinkers** [comment]
Feel free to improve the icons ;)

**Comment by teetrinkers** [comment]
I think ideally we'd have a white icon with black outlines and blue or red dot for Windows (like above) and a completely monochrome icon (including the notification) for OS X. Dropbox in my menu bar: 
dropbox mac

But I fear my icon skills aren't good enough for that.

**Comment by LongLiveCHIEF** [comment]
Maybe we could get @beejaymay to lend us a hand on this one? He makes quick
work of icon adjustments like this.

**Comment by teetrinkers** [comment]
Btw, this is what Slack looks like on Windows:
Slack notification area

On Mac they don't have the option to show an icon in the menu bar, but I kinda would like to have that option for Matterfront.

**Comment by teetrinkers** [comment]
I changed the const statements, made the application not quit on window close when the tray icon is enabled, and added documentation.

To dos still open:
1. Better icons
2. Unit tests
3. Consolidate events

**Comment by teetrinkers** [comment]
I wrote a basic unit test. It includes a partial stub of the electron api.

**Comment by LongLiveCHIEF** [comment]
Great! I'm creating a working branch for the evented stuff this afternoon, and will merge this into that branch, so it can be dropped in either 1.3 or 1.4.

**Pull request merged**
