### PR TITLE
Allow insecure resources like images to be loaded by Mattermost

### PR DESCRIPTION
**Pull request by daemongh**
This "fixes" the mixed content error displayed in the console of the Mattermost instance, issue #39.

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
This seems pretty extreme, and opens the product up to vulnerabilities.

**Comment by LongLiveCHIEF** [comment]
Can you resubmit after changing to `allowDisplayingInsecureContent` instead?

**Comment by daemongh** [comment]
I tried `allowDisplayingInsecureContent` however it does not seem to work for the webview.  After reading some more about it, it looks like it's because the `webview` element runs in a separate process and does not inherit any settings you apply to the app's window, [see documentation here (second paragraph)](https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md#the-webview-tag).

Unfortunately, the `disablewebsecurity` is not granular enough to allow loading of images, but disallow running of scripts.  Maybe this can be added as a preference setting down the road.

**Comment by LongLiveCHIEF** [comment]
I keep coming back to this. I'd rather not release software that is targeted for enterprises/organizations, with a very glaring security hole in an application.

If it comes down to security vs displaying images... I choose security. It would be irresponsible of us as software developers to release something with that kind of risk involved.

There has to be a better way to achieve what we need to do, without disabling CSP.

**Pull request closed without merging**
